// Code generated by timoni. DO NOT EDIT.
// Note that this file must have no imports and all values must be concrete.

package main

// Defaults
values: {
	image: {
		repository: "ghcr.io/stefanprodan/podinfo"
		tag:        "6.4.1"
		digest:     ""
	}
}
