// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: headers/headers.proto

package header

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HeaderServiceClient is the client API for HeaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeaderServiceClient interface {
	Header(ctx context.Context, in *HeaderRequest, opts ...grpc.CallOption) (*HeaderResponse, error)
}

type headerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeaderServiceClient(cc grpc.ClientConnInterface) HeaderServiceClient {
	return &headerServiceClient{cc}
}

func (c *headerServiceClient) Header(ctx context.Context, in *HeaderRequest, opts ...grpc.CallOption) (*HeaderResponse, error) {
	out := new(HeaderResponse)
	err := c.cc.Invoke(ctx, "/header.HeaderService/Header", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeaderServiceServer is the server API for HeaderService service.
// All implementations must embed UnimplementedHeaderServiceServer
// for forward compatibility
type HeaderServiceServer interface {
	Header(context.Context, *HeaderRequest) (*HeaderResponse, error)
	mustEmbedUnimplementedHeaderServiceServer()
}

// UnimplementedHeaderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHeaderServiceServer struct {
}

func (UnimplementedHeaderServiceServer) Header(context.Context, *HeaderRequest) (*HeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Header not implemented")
}
func (UnimplementedHeaderServiceServer) mustEmbedUnimplementedHeaderServiceServer() {}

// UnsafeHeaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeaderServiceServer will
// result in compilation errors.
type UnsafeHeaderServiceServer interface {
	mustEmbedUnimplementedHeaderServiceServer()
}

func RegisterHeaderServiceServer(s grpc.ServiceRegistrar, srv HeaderServiceServer) {
	s.RegisterService(&HeaderService_ServiceDesc, srv)
}

func _HeaderService_Header_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeaderServiceServer).Header(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/header.HeaderService/Header",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeaderServiceServer).Header(ctx, req.(*HeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HeaderService_ServiceDesc is the grpc.ServiceDesc for HeaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "header.HeaderService",
	HandlerType: (*HeaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Header",
			Handler:    _HeaderService_Header_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "headers/headers.proto",
}
