// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/api/apiserverinternal/v1alpha1

// Package v1alpha1 contains the v1alpha1 version of the API used by the
// apiservers themselves.
package v1alpha1
