extensions:
  health_check: {}
receivers:
  otlp:
    protocols:
      grpc:
  fluentforward:
    endpoint: 0.0.0.0:8006
processors:
  batch:
  # Will convert all monotonic, cumulative sums to monotonic, delta sums
  cumulativetodelta:
  transform:
    traces:
      queries:
        - truncate_all(attributes, 4095)
        - truncate_all(resource.attributes, 4095)
    logs:
      queries:
        - truncate_all(attributes, 4095)
        - truncate_all(resource.attributes, 4095)
exporters:
  logging:
    logLevel: $LOG_EXPORTER_LOG_LEVEL
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      "api-key": $NEW_RELIC_API_KEY
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [cumulativetodelta, batch]
      exporters: [logging, otlp]
    traces:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [logging, otlp]
    logs:
      receivers: [otlp, fluentforward]
      processors: [transform, batch]
      exporters: [logging, otlp]