apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "podinfo-istio.blue" . }}
  labels:
    app: {{ template "podinfo-istio.fullname" . }}
    chart: {{ template "podinfo-istio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    color: blue
    version: {{ .Values.blue.tag }}
spec:
  replicas: {{ .Values.blue.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "podinfo-istio.fullname" . }}
      color: blue
  template:
    metadata:
      labels:
        app: {{ template "podinfo-istio.fullname" . }}
        color: blue
        version: {{ .Values.blue.tag }}
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: podinfod
          image: "{{ .Values.blue.repository }}:{{ .Values.blue.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - ./podinfo
            - --port={{ .Values.containerPort }}
            - --level={{ .Values.logLevel }}
            - --random-delay={{ .Values.blue.faults.delay }}
            - --random-error={{ .Values.blue.faults.error }}
          env:
          - name: PODINFO_UI_COLOR
            value: blue
          {{- if .Values.blue.backend }}
          - name: PODINFO_BACKEND_URL
            value: {{ .Values.blue.backend }}
          {{- end }}
          {{- if .Values.blue.message }}
          - name: PODINFO_UI_MESSAGE
            value: {{ .Values.blue.message }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - podcli
              - check
              - http
              - localhost:{{ .Values.containerPort }}/healthz
          readinessProbe:
            exec:
              command:
              - podcli
              - check
              - http
              - localhost:{{ .Values.containerPort }}/readyz
          volumeMounts:
          - name: data
            mountPath: /data
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: data
        emptyDir: {}
