{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service.serviceAccountName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
{{- end -}}
