# Default values for podinfo-istio.

# host can be an external domain or a local one
host: podinfo
# if the host is an external domain must be exposed via the Gateway
exposeHost: false
timeout: 30s

# creates public-gateway.istio-system.svc.cluster.local
# no more than one Gateway can be created on a cluster
# if TLS is enabled the istio-ingressgateway-certs secret must exist in istio-system ns
# if you have a Gateway running you can set the name to your own gateway and turn off create
gateway:
  name: public-gateway
  create: false
  tls: false
  httpsRedirect: false

# authorise external https services
#externalServices:
#  - api.github.com
#  - apis.google.com
#  - googleapis.com

# stable release
# by default all traffic goes to blue
blue:
  replicas: 2
  repository: quay.io/stefanprodan/podinfo
  tag: "1.2.1"
  # green must have at at least one replica to set weight under 100
  weight: 100
  message:
  backend:
  faults:
    delay: false
    error: false

# canary release
# disabled with 0 replicas
green:
  replicas: 0
  repository: quay.io/stefanprodan/podinfo
  tag: "1.2.1"
  message:
  backend:
  routing:
  faults:
    delay: false
    error: false

# blue/green common settings
logLevel: info
containerPort: 9898
imagePullPolicy: IfNotPresent
resources:
  limits:
  requests:
    cpu: 1m
    memory: 16Mi
