name: Helm Composer
description: Renders HelmRelease CRD based on kustomize overlay structuress
runs:
  using: "composite"
  steps:

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: internal-gitops
        path: ./internal/
        retention-days: 90

    - name: Compose/Render HelmRelease CRD
      shell: bash
      env:
        MICROSERVICE: ${{ github.repository }}
      run: |
        shopt -s extglob
        mkdir rendered_templates
        MICROSERVICE="${MICROSERVICE##*/}"
        echo "MICROSERVICE=${MICROSERVICE}" >> "$GITHUB_ENV"
        for d in templates/!(base)/   
        do
          ENVIRONMENT=$(basename "$d")
          kubectl kustomize "$d" >> rendered_templates/"${MICROSERVICE}"-release-"$ENVIRONMENT".yaml
        done

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rendered-helmreleases
        path: ./rendered_templates/
        retention-days: 90