{
 "title": "Ambassador",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_server_total_connections)"
    }
   ]
  },
  {
   "title": "Total Heap Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_server_memory_heap_size)"
    }
   ]
  },
  {
   "title": "Envoy Servers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(envoy_server_live[5m]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "avg(envoy_server_uptime)" }
   ]
  },
  {
   "title": "Load Balancing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_http_ingress_http_rq_total[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod_name=~\".*ambassador.*\"}[1m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod_name=~\".*ambassador.*\"}[1m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\".*ambassador.*\"}[1m]))",
     "legendFormat": "cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\".*ambassador.*\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Downstream Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_ingress_http_downstream_rq_2xx[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(envoy_http_ingress_http_downstream_rq_4xx[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(envoy_http_ingress_http_downstream_rq_5xx[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Downstream Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "connections/sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_ingress_http_downstream_cx_http1_total[1m]))",
     "legendFormat": "HTTP/1.1"
    },
    {
     "expr": "sum(irate(envoy_http_ingress_http_downstream_cx_http2_total[1m]))",
     "legendFormat": "HTTP/2"
    },
    {
     "expr": "sum(irate(envoy_http_ingress_http_downstream_cx_websocket_total[1m]))",
     "legendFormat": "WebSocket"
    }
   ]
  },
  {
   "title": "Downstream Connections Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_listener_0_0_0_0_80_downstream_cx_length_ms{quantile=\"0.99\"})",
     "legendFormat": "0.99"
    }
   ]
  }
 ]
}