name: "Install Poetry"
description: "Install Poetry"
branding:
  icon: "code"
  color: "yellow"
inputs:
  version:
    description: "Version of Poetry to install"
    default: "2.1.3"
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache Poetry cache
      uses: actions/cache@v4
      with:
        path: ~/.local/
        key: venv-${{ runner.os }}-3.12-2.1.3

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.1.3

    - name: Cache Poetry packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: venv-${{ runner.os }}-3.12-2.1.3-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-3.12-2.1.3-
